## DTM과 TF-IDF를 사용하여 문서간 cosine_similarity 계산
### 1에 가까울수록 문장이 유사하다

In [45]:
from sklearn.feature_extraction.text import CountVectorizer

In [46]:
sentences = ["I like the dog","I Like the cat","dog like me","I like dog and cat"]

In [51]:
vector = CountVectorizer()
sen = vector.fit_transform(sentences).toarray()
print(sen)
print(vector.vocabulary_)

[[0 0 1 1 0 1]
 [0 1 0 1 0 1]
 [0 0 1 1 1 0]
 [1 1 1 1 0 0]]
{'like': 3, 'the': 5, 'dog': 2, 'cat': 1, 'me': 4, 'and': 0}


## Cosine Similarity
![ex_screenshot](cos_sim.png)

In [52]:
def cos_sim(A,B):
    return np.dot(A,B)/(np.linalg.norm(A)*np.linalg.norm(B))

def getMat(sequences):
    num = len(sequences)
    mat = np.eye(num)
    for i in range(num):
        for j in range(num):
            mat[i][j] = cos_sim(sequences[i],sequences[j])
    return mat

In [54]:
print(getMat(sen))

array([[1.        , 0.66666667, 0.66666667, 0.57735027],
       [0.66666667, 1.        , 0.33333333, 0.57735027],
       [0.66666667, 0.33333333, 1.        , 0.57735027],
       [0.57735027, 0.57735027, 0.57735027, 1.        ]])

In [55]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer().fit(sentences)
sen = tfidf.transform(sentences).toarray()

In [56]:
print(getMat(sen))

[[1.         0.63653684 0.4597522  0.39278488]
 [0.63653684 1.         0.1706786  0.47866007]
 [0.4597522  0.1706786  1.         0.34572237]
 [0.39278488 0.47866007 0.34572237 1.        ]]
